steps: [download, compile, prompts]

data:
  drive_folder: ""  # Google Drive folder URL or ID; leave empty to skip
  output_root: datasets
  resume: true
  patterns: [processed_result.csv, processed_results.csv]

compile:
  input_root: ${data.output_root}
  output_csv: datasets/compiled.csv

prompts:
  input_file: datasets/compiled.csv
  output_jsonl: datasets/train_prompts.jsonl
  seed: 42
  simple_frac: 0.2
  medium_frac: 0.4
  source_columns:
    organ: origin_folder
    finding: finding
    result: result
  organ_mapper:
    бп: "брюшная полость"
    ВНЧС: "височно-нижнечелюстной сустав"
    гм: "головной мозг"
    мж: "молочная железа"
    мт: "малый таз"